### ISSUE TITLE
JSON is deprecated now

### ISSUE THREAD

**Issue by nujabse** [bramvbilsen/Flutter-JSON-Storage-Tutorial#2]
Thanks a lot for your YouTube video tutorials! I've been following your teachings, but found an warning when typing your code in Android studio, seems like JSON is **deprecated** now, we may use **json** instead:
```
void createFile(Map<String, String> content, Directory dir, String fileName) {
    print("Creating file!");
    File file = new File(dir.path + "/" + fileName);
    file.createSync();
    fileExists = true;
    file.writeAsStringSync(JSON.encode(content));
  }
```

**Comment by bramvbilsen** [comment]
Thanks, could you make a pr for that? :)

**Comment by nujabse** [comment]
Sorry for my late reply, I've made a pr for that 🥂

**Comment by KlodianLula** [comment]
use lowercase ie.: json.encode
