### ISSUE TITLE
Where is the JSON file stored in my device?

### ISSUE THREAD

**Issue by samzzz** [bramvbilsen/Flutter-JSON-Storage-Tutorial#4]
Hello,
I checked in many folders including:

-  /storage/emulated/0 (= sdcard)
-  sdcard/Android/data
-  sdcard/data

But I cannot find the file .json stored in my device.

Where is it?
What string to add after your "dir.path" variable to reach the Download folder?
`jsonFile = new File(dir.path + "/" + fileName);`

Device: GALAXY S8+ SM-G955F. Android 8.0. Not Rooted
Flutter beta v0.5.1. Dart 2.0.0-dev.58.0. Windows 10
Thanks and regards

**Comment by KlodianLula** [comment]
you can do a print(jsonFile) to see the path :)
