### ISSUE TITLE
type Map<String, dynamic>' is not a subtype of type 'Map<String, String>' 

### ISSUE THREAD

**Issue by treflon** [bramvbilsen/Flutter-JSON-Storage-Tutorial#5]
**you should change 3 lines to make it work.**

Map<String, dynamic> fileContent;

Map<String, dynamic> content = {key: value};

Map<String, dynamic> jsonFileContent = json.decode(jsonFile.readAsStringSync());

**Comment by bramvbilsen** [comment]
This just means that you did not write a value of type `String`. In the tutorial though, we only use `String` keys and values, thus I do not see how this is relevant for this codebase.
